name: ESP32 Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Directory Structure
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pyserial

      - name: Compile Arduino Sketch
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: esp32:esp32:esp32
          sketch-names: ROV_Motion
          platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          additional-libraries: "Adafruit BNO055"
