name: Test Compile

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Arduino Sketch
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: esp32:esp32:esp32s3
          sketch-names: ROV_Motion.ino
          sketch-names-find-start: ROV_Motion
          platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          required-libraries: "Adafruit BNO055"
